<?php 

use kartik\grid\GridView;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\bootstrap4\Modal;
use yii\helpers\Url;
use yii\data\SqlDataProvider;
use app\models\Xscadconsc;


echo 'ciao';
$columns = [

    ['label' => 'Cd_CGConto_Banca',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'Cd_CGConto_Banca',
    ],
    ['label' => 'DataScadenza',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'DataScadenza',
    ],
    ['label' => 'Cd_CF',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'Cd_CF',
    ],
    ['label' => 'Descrizione',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'Descrizione',
    ],
    ['label' => 'DataFattura',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'DataFattura',
    ],
    ['label' => 'NumFattura',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'NumFattura',
    ],
    ['label' => 'TipoRata',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'TipoRata',
    ],
    ['label' => 'Emessa',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'Emessa',
    ],
    ['label' => 'Contabilizzata',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'Contabilizzata',
    ],
    ['label' => 'Insoluta',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'Insoluta',
    ],
    ['label' => 'Cd_VL',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'Cd_VL',
    ],
    ['label' => 'ImportoE',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'ImportoE',
    ],
    ['label' => 'ImportoV',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'ImportoV',
    ],
    ['label' => 'ImportoDaPagareE',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'ImportoDaPagareE',
    ],
    ['label' => 'ImportoDaPagareV',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'ImportoDaPagareV',
    ],
    ['label' => 'Pagata',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'Pagata',
    ],
/*['label' => 'FTE_TipoPagamento',
'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
//'class' => 'kartik\grid\ExpandRowColumn',
'width' => '3%',
'attribute' => 'FTE_TipoPagamento',
],*/
    ['label' => 'ImportoDare',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'ImportoDare',
    ],
    ['label' => 'ImportoAvere',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'ImportoAvere',
    ],
    ['label' => 'Saldo',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'Saldo',
    ],
    ['label' => 'Stato_Cli',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'Stato_Cli',
    ],
    ['label' => 'Settore_Cli',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'Settore_Cli',
    ], ['label' => 'cd_sottocommessa',
        'headerOptions' => ['class' => 'card-header bg-' . $usrgrid . ' text-white'],
        //'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '3%',
        'attribute' => 'cd_sottocommessa',
    ],
];



echo
GridView::widget([
    'dataProvider' => $provider, 'resizableColumnsOptions' => ['resizeFromBody' => true],
    'persistResize' => true,
    'resizeStorageKey' => Yii::$app->user->id . '-' . date('m') . 'sc',
    'toggleDataContainer' => ['class' => 'btn-group mr-2 me-2'],
    'columns' => $columns,
    'export' => [
        'showConfirmAlert' => false,
        'target' => GridView::TARGET_BLANK,
        GridView::PDF => [
            'label' => Yii::t('kvgrid', 'PDF'),
            'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
            'iconOptions' => ['class' => 'text-danger'],
            'showHeader' => true,
            'showPageSummary' => true,
            'showFooter' => true,
            'showCaption' => true,
            'filename' => Yii::t('kvgrid', 'Portal pdf export'),
            'alertMsg' => Yii::t('kvgrid', 'The PDF export file will be generated for download.'),
            'options' => ['title' => Yii::t('kvgrid', 'Portable Document Format')],
            'mime' => 'application/pdf',
            'config' => [
                'mode' => 'c',
                'format' => 'A4-L',
                'destination' => 'D',
                'marginTop' => 20,
                'marginBottom' => 20,
                'cssFile' => 'https: //use.fontawesome.com/releases/v5.3.1/css/all.css',
                'cssInline' => '.kv-wrap{padding:20px;}' .
                '.kv-align-center{text-align:center;}' .
                '.kv-align-left{text-align:left;}' .
                '.kv-align-right{text-align:right;}' .
                '.kv-align-top{vertical-align:top!important;}' .
                '.kv-align-bottom{vertical-align:bottom!important;}' .
                '.kv-align-middle{vertical-align:middle!important;}' .
                '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
                '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
                /*   'methods' => [
                'SetHeader' => [
                ['odd' => $pdfHeader, 'even' => $pdfHeader],
                ],
                'SetFooter' => [
                ['odd' => $pdfFooter, 'even' => $pdfFooter],
                ],
                ],*/
                'options' => [
                    //   'title' => $title,
                    'subject' => Yii::t('kvgrid', 'PDF'),
                    'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf'),
                ],
                'contentBefore' => '',
                'contentAfter' => '',
            ],
        ],
    ], 'panel' => [
        'type' => $ris['grid_color'],
        'heading' => '<i class="fas  fa-book"></i> x_ScadCon _SC',
    ],
    'responsive' => true,
    'resizableColumns' => true,
    'showPageSummary' => true,
    'pjax' => false,
]);

?>